project:
  type: website
  output-dir: docs
  resources: files

website:
  title: "Kate Saunders"
  favicon: logo.png
  site-url: https://katerobsau.github.io/website-quarto/
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Education
        href: education.qmd
      - text: Publications
        href: publications.qmd
      - text: Talks
        href: talks.qmd
      - text: Software
        href: software.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Students
        href: students.qmd
      - text: Blog
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/katerobsau/website-quarto      

body-footer: | 
  Copyright:  Kate Saunders, 2026

date-format: "D MMMM YYYY"

format:
  html:
    theme: 
      - pulse
      - custom.scss
    toc: true

