---
title: "Graduated and current PhD students"
---

```{r}
#| echo: false
#| message: false
library(readr)
library(dplyr)
library(flextable)
st <- read_csv("students.csv")
st_tbl <- st |>
  select(name, year, url, from, topic, `co-advisors`) |>
  mutate(year = as.character(year)) |>
  flextable()
st_tbl <- compose(
  x = st_tbl,
  j = "name",
  value = as_paragraph(hyperlink_text(x=name, url=url, 
     props = officer::fp_text(color = "#a96469")))) |>
  delete_columns(j = "url")  
st_tbl <- width(x = st_tbl, 
                j = "topic", 
                width = 5)
st_tbl
```

```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-width: 10
#| fig-height: 5
#| out-width: 100%
library(ggplot2)
library(maps)
library(ggthemes)
library(ggrepel)

# Import the data with coordinates
world <- map_data("world") |>
  filter(region != "Antarctica")

# Plot the map. group = group connects the points in the correct order
ggplot() + 
  geom_polygon(data = world, aes(x = long, 
                                 y = lat, 
                                 group = group),
               fill="grey80", color="white") +
  geom_point(data=st, aes(x=lon, y=lat), 
             colour = "#1e5868") +
  geom_text_repel(data=st, aes(x=lon, y=lat, label=name), 
                  colour = "#1e5868", max.overlaps = 20) +
  theme_map() 

```