---
title: "Teaching resources"
---

## University courses

```{r}
#| echo: false
#| message: false
library(readr)
library(dplyr)
library(gt)
library(glue)
teaching <- read_csv("teaching.csv")
teaching <- teaching |>
  mutate(titlelink = glue("[{title}]({link})"))
teaching |>
  select(number, titlelink, location, description) |>
  gt() |>
    gt::fmt_markdown(columns = titlelink) |>
    cols_label(titlelink = "title") |> 
    gt::cols_width(
      number ~ px(150),
      titlelink ~ px(400),
      location ~ px(150),
      description ~ px(300)) |>
  cols_align("left")
```

## Workshops

```{r}
#| echo: false
#| message: false
library(readr)
library(dplyr)
library(gt)
library(glue)
library(lubridate)
ws <- read_csv("workshops.csv")
ws <- ws |>
  mutate(titlelink = glue("[{title}]({link})")) |>
  mutate(date = dmy(date))
ws |>
  arrange(desc(date)) |>
  select(date, titlelink, location, details) |>
  gt() |>
    gt::fmt_markdown(columns = titlelink) |>
    cols_label(titlelink = "title") |> 
    gt::cols_width(
      date ~ px(150),
      titlelink ~ px(450),
      location ~ px(250),
      details ~ px(150)) |>
  cols_align("left")
```

And more than 30 workshops across the globe over many years.